eeSea/Models/Vessel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace eeSea.Models
{
    public class Vessel
    {
        public long Id { get; set; }

        public string HullCode { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime BuiltDate { get; set; }

        public int NominalCapacity { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public decimal Length { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public decimal Breadth { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public decimal Beam { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public decimal Draft { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.00}")]
        public decimal MaxSpeed { get; set; }

        public virtual  VesselName VesselName { get; set; }
        public virtual VesselOwner VesselOwner { get; set; }
        public virtual VesselOperator VesselOperator { get; set; }
    }
}

eeSea/Controllers/VesselsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eeSea.com.eesea.ws;
using eeSea.Models;
using eeSea.Models.ViewModels;

namespace eeSea.Controllers
{
    public class VesselsController : Controller
    {

        Transportal eeSeaWS = new Transportal();
        private EeSeaContext db = new EeSeaContext();
        //
        // GET: /Vessels/
        //[OutputCache(Duration = 300)]
        public ActionResult Index()
        {

            var vesselsTemp = eeSeaWS.GetAllVessels(true);

            var vesselsNamesTemp = vesselsTemp.Where(v => v.Name.Length > 0)
                                             .Select(v => new
                                             {
                                                 Id = v.Id,
                                                 Name = v.Name[0].Name
                                             })
                                             .Distinct();

            var vesselsOwnersTemp = vesselsTemp.Where(v => v.Owner.Length > 0)
                                            .GroupBy(v => v.Owner[0].Company.Name)
                                            .Select(v => v.First().Owner[0].Company);

            var vesselsOperatorsTemp = vesselsTemp.Where(v => v.Operator.Length > 0)
                                            .GroupBy(v => v.Operator[0].Company.Name)
                                            .Select(v => v.First().Operator[0].Company);




            ViewBag.Vessels = vesselsNamesTemp;
            ViewBag.Owners = vesselsOwnersTemp;
            ViewBag.Operators = vesselsOperatorsTemp;
            return View();
        }


        public ActionResult GetVesselsResults(string VesselId = "0", string OwnerId = "0", string OperatorId = "0")
        {
            long vesselId;
            long ownerId;
            long operatorId;
            if (VesselId.Trim() != "")
            {
                vesselId = long.Parse(VesselId);
            }
            else
            {
                vesselId = 0;
            }

            if (OwnerId.Trim() != "")
            {
                ownerId = long.Parse(OwnerId);
            }
            else
            {
                ownerId = 0;
            }

            if (OperatorId.Trim() != "")
            {
                operatorId = long.Parse(OperatorId);
            }
            else
            {
                operatorId = 0;
            }
            var vesselsTemp = eeSeaWS.GetAllVessels(true)
                                     .Select(vessel => new eeSea.Models.Vessel
                                       {
                                           Id = vessel.Id,
                                           HullCode = vessel.HullCode,
                                           BuiltDate = vessel.BuiltDate,
                                           NominalCapacity = vessel.NominalCapacity,
                                           Length = vessel.Length,
                                           Breadth = vessel.Breadth,
                                           Beam = vessel.Beam,
                                           Draft = vessel.Draft,
                                           MaxSpeed = vessel.MaxSpeed,
                                           VesselName = vessel.Name.Length == 0 ? null : new eeSea.Models.VesselName
                                           {
                                               Id = vessel.Name[0].Id,
                                               Name = vessel.Name[0].Name,
                                               Date = vessel.Name[0].Date
                                           },
                                           VesselOwner = vessel.Owner.Length == 0 ? null : new eeSea.Models.VesselOwner
                                           {
                                               Id = vessel.Owner[0].Id,
                                               Date = vessel.Owner[0].Date,
                                               Company = vessel.Owner.Length == 0 ? null : new Models.Company
                                               {
                                                   Id = vessel.Owner[0].Company.Id,
                                                   Code = vessel.Owner[0].Company.Code,
                                                   Name = vessel.Owner[0].Company.Name
                                               }
                                           },
                                           VesselOperator = vessel.Operator.Length == 0 ? null : new Models.VesselOperator
                                           {
                                               Id = vessel.Operator[0].Id,
                                               Date = vessel.Operator[0].Date,
                                               Company = vessel.Operator.Length == 0 ? null : new Models.Company
                                                            {
                                                                Id = vessel.Operator[0].Company.Id,
                                                                Code = vessel.Operator[0].Company.Code,
                                                                Name = vessel.Operator[0].Company.Name
                                                            }
                                           }
                                       });
            if (vesselId != 0)
            {

                vesselsTemp = vesselsTemp.Where(l => l.Id == vesselId).ToList();

            }

            if (ownerId != 0)
            {
                vesselsTemp = vesselsTemp.Where(l => l.VesselOwner != null);
                vesselsTemp = vesselsTemp.Where(l => l.VesselOwner.Company.Id == ownerId).ToList();

            }

            if (operatorId != 0)
            {
                vesselsTemp = vesselsTemp.Where(l => l.VesselOperator != null);
                vesselsTemp = vesselsTemp.Where(l => l.VesselOperator.Company.Id == operatorId).ToList();

            }
            return View(vesselsTemp);
        }


        public ActionResult GetVesselsResultsByTerm(string term)
        {
            term = term.Replace("%", " ");
            var vesselsTemp = eeSeaWS.GetAllVessels(true)
                                     .Select(vessel => new eeSea.Models.Vessel
                                     {
                                         Id = vessel.Id,
                                         HullCode = vessel.HullCode,
                                         BuiltDate = vessel.BuiltDate,
                                         NominalCapacity = vessel.NominalCapacity,
                                         Length = vessel.Length,
                                         Breadth = vessel.Breadth,
                                         Beam = vessel.Beam,
                                         Draft = vessel.Draft,
                                         MaxSpeed = vessel.MaxSpeed,
                                         VesselName = vessel.Name.Length == 0 ? null : new eeSea.Models.VesselName
                                         {
                                             Id = vessel.Name[0].Id,
                                             Name = vessel.Name[0].Name,
                                             Date = vessel.Name[0].Date
                                         },
                                         VesselOwner = vessel.Owner.Length == 0 ? null : new eeSea.Models.VesselOwner
                                         {
                                             Id = vessel.Owner[0].Id,
                                             Date = vessel.Owner[0].Date,
                                             Company = vessel.Owner.Length == 0 ? null : new Models.Company
                                             {
                                                 Id = vessel.Owner[0].Company.Id,
                                                 Code = vessel.Owner[0].Company.Code,
                                                 Name = vessel.Owner[0].Company.Name
                                             }
                                         },
                                         VesselOperator = vessel.Operator.Length == 0 ? null : new Models.VesselOperator
                                         {
                                             Id = vessel.Operator[0].Id,
                                             Date = vessel.Operator[0].Date,
                                             Company = vessel.Operator.Length == 0 ? null : new Models.Company
                                             {
                                                 Id = vessel.Operator[0].Company.Id,
                                                 Code = vessel.Operator[0].Company.Code,
                                                 Name = vessel.Operator[0].Company.Name
                                             }
                                         }
                                     })
                                     .Where(vessel => vessel.VesselName != null && vessel.VesselName.Name.ToLower().Contains(term.ToLower()))
                                    ;

            return View("GetVesselsResults", vesselsTemp);

        }






        public ActionResult VesselInfos(int id)
        {
            var vesselTemp = eeSeaWS.GetAllVessels(true)
                                     .Select(vessel => new eeSea.Models.Vessel
                                     {
                                         Id = vessel.Id,
                                         HullCode = vessel.HullCode,
                                         BuiltDate = vessel.BuiltDate,
                                         NominalCapacity = vessel.NominalCapacity,
                                         Length = vessel.Length,

eeSea/Views/Vessels/GetVesselsResults.cshtml
@model IEnumerable<eeSea.Models.Vessel>
@{
    Layout = null;
}
<link href="@Url.Content("~/Content/ui.jqgrid.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="@Url.Content("~/Scripts/grid.locale-en.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.jqGrid.min.js")"></script>
<script type="text/javascript">



    var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-33927253-1']);

    _gaq.push(['_setDomainName', 'eesea.com']);

    _gaq.push(['_trackPageview']);



    (function () {

        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();

 

</script>
 <table class="List" align="left" id="ListItems">
    <thead>
        <tr>
            <th   scope="col"  width="25%">Id</th>
            <th   scope="col"  width="25%">Vessel Name</th>
            <th   scope="col"  width="25%">Owner</th>
            <th  scope="col"  width="25%">Operator</th>
            <th  scope="col"  width="25%">IMO Hull Code</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr id="@item.Id">
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VesselName.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VesselOwner.Company.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VesselOperator.Company.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HullCode)
                </td>
            </tr>
        }
    </tbody>
</table>
<div id="pager" class="scroll" style="text-align: center;">
</div>
<script type="text/javascript">
    //<![CDATA[

    $(function () {

        myGrid2 = $("#ListItems");
        tableToGrid(myGrid2, {
            rowNum:10, 
            rowList:[10,20,30], 
            pager: '#pager', 
            sortname: 'id', 
            viewrecords: false, 
            sortorder: "desc", 
            caption:"Vessels Search Results:",
           colNames: ['Id', 'Vessel Name', 'Owner', 'Operator', 'IMO Hull Code'],
                    colModel: [
                        { name: 'Id', index: 'Id', width: 30, hidden: true },
                        { name: 'Vessel_Name', index: 'Vessel_Name', width: 120 },
                        { name: 'Owner', index: 'Owner', width: 120 },
                        { name: 'Operator', index: 'Operator', width: 120 },
                        { name: 'IMO_Hull_Code', index: 'IMO_Hull_Code', width: 120 } 
                    ],
            height: 450,    
            autowidth: true,
            forceFit: true,      
            onSelectRow: function(rowid) {

                var id = $(this).getCell(rowid,0);
                //alert("-" + id + "-");
                $("#data-grid").html("")
                .load("@Url.Content("~/Vessels/VesselInfos/")" + $.trim(id));
                
            }
        });

        //autowidth: true,
        //width: '100%'
    });
</script>

eeSea/Views/Vessels/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@model eeSea.Models.Region
@{
    
    
    
}
<script type="text/javascript">



    var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-33927253-1']);

    _gaq.push(['_setDomainName', 'eesea.com']);

    _gaq.push(['_trackPageview']);



    (function () {

        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();

 

</script>
<script src="@Url.Content("~/Content/js/fcts.js")" type="text/javascript"></script>
<table width="100%" border="0" id="tblContent">
    <tr>
        <td id="tdCont" height="500px" valign="top" align="center">
            <div id="loading" style="display: none;" class="innerDiv">
                <span style="color: #EE7409; font-size: 13px;">Please wait while loading data ...</span><br />
                <img style="align: center;" src="../Content/Images/ajax-loader.gif" alt="Loading, please wait" />
            </div>
            <div id="data-grid" style="overflow: auto;">
            </div>
        </td>
        <td valign="top" id="toggle">
            <div id='sideToggleShow'>
            </div>
            <div id='sideToggleHide' style="display: none">
            </div>
        </td>
        <td id='side' class='sideList' valign="top">
            @using (Ajax.BeginForm("GetVesselsResults", "Vessels", new AjaxOptions { UpdateTargetId = "data-grid", LoadingElementDuration = 1000, LoadingElementId = "loading", HttpMethod = "GET" }))
            {
               <table border="0" height="450px">
                    <tr >
                        <td  align="left" height="25px" colspan="2">
                            Find a Vessel
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">
                            Vessel Name:
                        </td>
                        <td>@Html.DropDownList("VesselId", new SelectList(ViewBag.Vessels, "Id", "Name"), "-- Select Vessel Name --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">
                            Owner:
                        </td>
                        <td>@Html.DropDownList("OwnerId", new SelectList(ViewBag.Owners, "Id", "Name"), "-- Select Owner --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">
                            Operator:
                        </td>
                        <td>@Html.DropDownList("OperatorId", new SelectList(ViewBag.Operators, "Id", "Name"), "-- Select Operator --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">
                        </td>
                        <td>
                            <input value="Go" type="submit" class="btnSearch" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                        </td>
                    </tr>
                </table>
              
            }
            <table height="50px" border="0" width="100%">
                <tr>
                    <td colspan="2" height="25px">
                        <table width="">
                            <tr>
                                <td width="90%">
                                    <input id="SearchBox" type="text" style="width: 185px" class="ui-widget search-dropdown"
                                        value="Search..." />
                                </td>
                                <td>
                                    <input value="Go" type="submit" class="btnSearch2" />
                                </td>
                            </tr>
                        </table>
                    </td>
                    <td>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<script type="text/javascript">
    $(document).ready(function () {

    //autocomplete text search
        $("#SearchBox").autocomplete({
            source: '@Url.Action("GetVesselsAttributes", "Vessels")',
            select: function(event, ui) {
            /*
            $("#data-grid").html("")
                .load(encodeURI("@Url.Content("~/Vessels/GetVesselsResultsByTerm/?term=")" + ui.item.label));
            */
                } 
        });

        $("#SearchBox").focus(function (event,ui) {
            $(this).val('');
       });

        $("#SearchBox").keypress(function (event,ui) {
            //alert(event.keyCode);
            if (event.keyCode == '13') { 
            }
        });

         $(".btnSearch2").click(function () {          
            $("#data-grid").html("")
                .load(encodeURI("@Url.Content("~/Vessels/GetVesselsResultsByTerm/?term=")" + $("#SearchBox").val()));
            
                 
        });


         toggleSideBar();
    });

      
     
   

</script>

eeSea/Views/Vessels/VesselInfos.cshtml
@model eeSea.Models.Vessel
@{
    Layout = null;
    var VesselDynamicAttributes = (List<eeSea.Models.ViewModels.VesselDynamicAttributesViewModel>)ViewBag.VesselDynamicAttributes;
}
<script src="@Url.Content("~/Scripts/jquery-1.8.3.js")" type="text/javascript"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.galleriffic.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.opacityrollover.js")"></script>
<link href="@Url.Content("~/Content/Gallery.css")" rel="Stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/ui.jqgrid.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="@Url.Content("~/Scripts/grid.locale-en.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.jqGrid.min.js")"></script>
<script type="text/javascript">



    var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-33927253-1']);

    _gaq.push(['_setDomainName', 'eesea.com']);

    _gaq.push(['_trackPageview']);



    (function () {

        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();

 

</script>
<table border="0" align="left" width="100%">
    <tr>
        <td align="left" colspan="2" height="30px" valign="top">
            <h3 class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                IMO hull code: @Model.HullCode
            </h3>
        </td>
    </tr>
    <tr>
        <td width="40%" valign="top">
            <table width="100%" border="0" align="left" class="tblInfos ui-widget ui-widget-content ui-corner-all">
                <tr>
                    <td align="left" colspan="2"  >
                        <h4 class="titleTblInfos  ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                            Static attributes</h4>
                    </td>
                </tr>
                <tr align="left" >
                    <td width="30%" height="25px">
                        <b>Shipyard</b>
                    </td>
                    <td>
                        @Model.VesselName.Name
                    </td>
                </tr>
                <tr align="left" >
                    <td height="25px">
                        <b>Hull start date</b>
                    </td>
                    <td>
                        @Model.BuiltDate.ToString("dd/MM/yyyy")
                    </td>
                </tr>
                <tr align="left" >
                    <td height="25px">
                        <b>Hull completion date</b>
                    </td>
                    <td>
                        lorem ipsum
                    </td>
                </tr>
                <tr align="left" >
                    <td height="25px">
                        <b>Vessel type</b>
                    </td>
                    <td>
                        lorem ipsum
                    </td>
                </tr>
                <tr align="left" >
                    <td height="25px">
                        <b>Length</b>
                    </td>
                    <td>
                        @Model.Length meter
                    </td>
                </tr>
                <tr align="left" >
                    <td  height="25px">
                        <b>Breadth</b>
                    </td>
                    <td>
                        @Model.Breadth meter
                    </td>
                </tr>
                <tr align="left" >
                    <td  height="25px">
                        <b>Draught</b>
                    </td>
                    <td>
                        @Model.Draft meter
                    </td>
                </tr>
                <tr align="left" >
                    <td height="25px">
                        <b>Deadweight</b>
                    </td>
                    <td>
                        lorem ipsum tons
                    </td>
                </tr>
                <tr align="left" >
                    <td  height="25px">
                        <b>Max speed</b>
                    </td>
                    <td>
                        @Model.MaxSpeed knots
                    </td>
                </tr>
                <tr align="left" >
                    <td  height="25px">
                        <b>Nominal capacity</b>
                    </td>
                    <td>
                        @Model.NominalCapacity TEUs
                    </td>
                </tr>
            </table>
        </td>
        <td valign="top" align="left" >
            <div id="gallery" class="content">
                <div class="slideshow-container">
                    <div id="slideshow" class="slideshow">
                    </div>
                    <div id="thumbs" class="navigation">
                        <ul class="thumbs noscript">
                            <li><a class="thumb" name="optionalCustomIdentifier" href="@Url.Content("~/Content/vessels-imgs/11/1.jpg")" title="your image title">
                                <img width="80px" src="@Url.Content("~/Content/vessels-imgs/11/1.jpg")" alt="your image title again for graceful degradation" />
                            </a></li>
                            <li><a class="thumb" name="optionalCustomIdentifier" href="@Url.Content("~/Content/vessels-imgs/11/2.jpg")" title="your image title">
                                <img  width="80px" src="@Url.Content("~/Content/vessels-imgs/11/2.jpg")" alt="your image title again for graceful degradation" />
                            </a></li>
                            <li><a class="thumb" name="optionalCustomIdentifier" href="@Url.Content("~/Content/vessels-imgs/11/3.jpg")" title="your image title">
                                <img   width="80px" src="@Url.Content("~/Content/vessels-imgs/11/3.jpg")" alt="your image title again for graceful degradation" />
                            </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2" height="240px" valign="top">
            @{
                int i = 0;
                int total = (int)ViewBag.Total;  
            }
            <table class="List" align="left" id="ListItems">
                <tr>
                    <th scope="col">
                        Version
                    </th>
                    <th scope="col">
                        Vessel Name
                    </th>
                    <th scope="col">
                        Valid From
                    </th>
                    <th scope="col">
                        Owner Name
                    </th>
                    <th scope="col">
                        Operator Name
                    </th>
                </tr>
                @foreach (var item in (List<eeSea.Models.ViewModels.VesselDynamicAttributesViewModel>)ViewBag.VesselDynamicAttributes)
                {
                    <tr>
                        <td>@(total - i)</td>
                        <td>@Html.DisplayFor(modelItem => item.VesselName)</td>
                        <td>@item.VesselNameDate.ToString("dd-MM-yyyy")</td>
                        <td>@item.OwnerName</td>
                        <td>@item.OperatorName</td>
                    </tr>
                     
                       i = i + 1;


                }
            </table>
        </td>
    </tr>
</table>
<br />
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        // We only want these styles applied when javascript is enabled
        $('div.navigation').css({ 'width': '2px', 'float': 'left' });
        $('div.content').css('display', 'block');

        // Initially set opacity on thumbs and add
        // additional styling for hover effect on thumbs
        var onMouseOutOpacity = 0.67;
        $('#thumbs ul.thumbs li').opacityrollover({
            mouseOutOpacity: onMouseOutOpacity,
            mouseOverOpacity: 1.0,
            fadeSpeed: 'fast',
            exemptionSelector: '.selected'
        });

        // Initialize Advanced Galleriffic Gallery
        var gallery = $('#thumbs').galleriffic({
            delay: 2500,
            numThumbs: 15,
            preloadAhead: 10,
            enableTopPager: true,
            enableBottomPager: true,
            maxPagesToShow: 7,
            imageContainerSel: '#slideshow',
            controlsContainerSel: '#controls',
            captionContainerSel: '#caption',
            loadingContainerSel: '#loading',
            renderSSControls: true,
            renderNavControls: true,
            playLinkText: 'Play Slideshow',
            pauseLinkText: 'Pause Slideshow',
            prevLinkText: '&lsaquo; Previous Photo',
            nextLinkText: 'Next Photo &rsaquo;',
            nextPageLinkText: 'Next &rsaquo;',
            prevPageLinkText: '&lsaquo; Prev',
            enableHistory: false,
            autoStart: false,
            syncTransitions: true,
            defaultTransitionDuration: 900,
            onSlideChange: function (prevIndex, nextIndex) {
                // 'this' refers to the gallery, which is an extension of $('#thumbs')
                this.find('ul.thumbs').children()
							.eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
							.eq(nextIndex).fadeTo('fast', 1.0);
            },
            onPageTransitionOut: function (callback) {
                this.fadeTo('fast', 0.0, callback);
            },
            onPageTransitionIn: function () {
                this.fadeTo('fast', 1.0);
            }
        });
    });
</script>
<script type="text/javascript">
    //<![CDATA[

    $(function () {

        myGrid2 = $("#ListItems");
        tableToGrid(myGrid2, {
            rowNum:10, 
            rowList:[10,20,30], 
            pager: '#pager', 
              
            viewrecords: false, 
            sortorder: "desc", 
            height:220,
            autowidth: true,            
            forceFit: true,    
            caption:"Dynamic attributes:",
            colNames: ['Version', 'Vessel Name', 'Valid From', 'Owner Name', 'Operator Name'],
                    colModel: [
                        { name: 'Version', index: 'Version', width: 50 , align: 'center'   },
                        { name: 'Vessel_Name', index: 'Vessel_Name', width: 90 , align: 'center'    },
                        { name: 'Valid_From', index: 'Valid_From', width: 50  , align: 'center'   },
                        { name: 'Owner_Name', index: 'Owner_Name' , width: 70 , align: 'center'   },
                        { name: 'Operator_Name', index: 'Operator_Name', width: 70, align: 'center'     } 
                    ],
        });

        //autowidth: true,
        //width: '100%'
    });
</script>