eeSea/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace eeSea.Models
{
    [Table("TLocation", Schema = "dbo")]
    public class Location
    {
        [Key]
        [Column("Location_ID", TypeName = "bigint")]
        public long Id { get; set; }

        [Column("Location_Code", TypeName = "nvarchar")]
        public string Code { get; set; }

        [Column("Location_Name", TypeName = "nvarchar")]
        public string Name { get; set; }

         
        [DisplayFormat(DataFormatString = "{0:0.000000}")]
        [Column("Location_Latitude", TypeName = "numeric")]
        public decimal  Latitude { get; set; }

        [DisplayFormat(DataFormatString = "{0:0.000000}")]
        [Column("Location_Longitude", TypeName = "numeric")]
        public decimal  Longitude { get; set; }

        /* 
        [Column("Location_Region", TypeName = "bigint")]
        public long LocationRegionID { get; set; }
        */
        
        public virtual Region Region { get; set; }
        public virtual City City { get; set; }
       
    }
}

eeSea/Controllers/LocationsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Collections;
using eeSea.Models;
using eeSea.com.eesea.ws;
using System;
using System.Drawing;


namespace eeSea.Controllers
{
    public class LocationsController : Controller
    {
        //
        // GET: /Locations/
        //private EeSeaContext db = new EeSeaContext();
        Transportal eeSeaWS = new Transportal();


        public ActionResult Index()
        {
            List<eeSea.Models.Location> locations = null;
            var regions = eeSeaWS.GetAllRegions();
            ViewBag.Regions = regions;
            ViewBag.Locations = locations;

            List<eeSea.Models.Location> Alllocations = GetAllLocations();
            ViewBag.AllLocations = Alllocations;
            Session["AllLocations"] = Alllocations;
            // List<eeSea.Models.Link> AlllocationLinks = null;
            ViewBag.AllLocationLinks = null;
            return View();
        }

        public ViewResult LocationInfos(int id)
        {
            var locationTemp = eeSeaWS.GetAllLocations()
                                  .Select(location => new Models.Location
                                    {
                                        Id = location.Id,
                                        Code = location.Code,
                                        Name = location.Name,
                                        Latitude = location.Latitude,
                                        Longitude = location.Longitude,
                                        Region = new eeSea.Models.Region { Id = location.Region.Id, Name = location.Region.Name },
                                        City = new eeSea.Models.City
                                        {
                                            Id = location.MLocation.Id,
                                            Code = location.MLocation.Code,
                                            Name = location.MLocation.Name,
                                            State = new Models.State { Id = location.MLocation.State.Id, Code = location.MLocation.State.Code, Name = location.MLocation.State.Name },
                                            Country = new Models.Country { Id = location.MLocation.Country.Id, Code = location.MLocation.Country.Code, Name = location.MLocation.Country.Name },
                                            Continent = new Models.Continent { Id = location.MLocation.Continent.Id, Code = location.MLocation.Continent.Code, Name = location.MLocation.Continent.Name }
                                        }
                                    })
                                  .Where(l => l.Id == id).SingleOrDefault();
            return View(locationTemp);
        }

        public ActionResult Lookup()
        {
            return View();
        }

        //return Json Locations for Drop Down List

        public ActionResult GetLocationByRegionId(string regionID)
        {
            var locations = default(IList);

            if (!string.IsNullOrEmpty(regionID))
            {
                long? tempRegionId = long.Parse(regionID);
                locations = eeSeaWS.GetAllLocations()
                                   .Where(l => l.Region.Id == tempRegionId)
                                   .Select(l => new { l.Name, l.Code })
                                   .OrderBy(l => l.Name).ToList();
            }
            return Json(locations, JsonRequestBehavior.AllowGet);

        }


        public ActionResult GetLocationIdsByRegionId(string regionID)
        {
            var locations = default(IList);

            if (!string.IsNullOrEmpty(regionID))
            {
                long? tempRegionId = long.Parse(regionID);
                locations = eeSeaWS.GetAllLocations()
                                   .Where(l => l.Region.Id == tempRegionId)
                                   .Select(l => new { l.Name, l.Id })
                                   .OrderBy(l => l.Name).ToList();
            }
            return Json(locations, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetLocationsResuls(string RegionId = "0", string LocationCode = "0")
        {
            //var locations = default(IList);
            var locations = default(IList);
            long regionID = long.Parse(RegionId);
            string locationCode = LocationCode;
            var locationsTemp = eeSeaWS.GetAllLocations()
                                       .Select(location => new eeSea.Models.Location
                                       {
                                           Id = location.Id,
                                           Code = location.Code,
                                           Name = location.Name,
                                           Latitude = location.Latitude,
                                           Longitude = location.Longitude,
                                           Region = new eeSea.Models.Region { Id = location.Region.Id, Name = location.Region.Name },
                                           City = new eeSea.Models.City
                                           {
                                               Id = location.MLocation.Id,
                                               Code = location.MLocation.Code,
                                               Name = location.MLocation.Name,
                                               State = new Models.State { Id = location.MLocation.State.Id, Code = location.MLocation.State.Code, Name = location.MLocation.State.Name },
                                               Country = new Models.Country { Id = location.MLocation.Country.Id, Code = location.MLocation.Country.Code, Name = location.MLocation.Country.Name },
                                               Continent = new Models.Continent { Id = location.MLocation.Continent.Id, Code = location.MLocation.Continent.Code, Name = location.MLocation.Continent.Name }
                                           }
                                       })
                                       .Where(l => l.Region.Id == regionID);

            if (locationCode != null && locationCode != "0")
            {
                locations = locationsTemp.Where(l => l.Code == locationCode).ToList();

            }
            else
            {
                locations = locationsTemp.ToList();
            }

            ViewBag.Locations = locations;
            return View(locations);
        }

        public List<Models.Location> GetAllLocations()
        {
            return eeSeaWS.GetAllLocations().Select(location => new Models.Location
                                    {
                                        Id = location.Id,
                                        Code = location.Code,
                                        Name = location.Name,
                                        Latitude = location.Latitude,
                                        Longitude = location.Longitude,
                                        Region = new eeSea.Models.Region { Id = location.Region.Id, Name = location.Region.Name },
                                        City = new eeSea.Models.City
                                        {
                                            Id = location.MLocation.Id,
                                            Code = location.MLocation.Code,
                                            Name = location.MLocation.Name,
                                            State = new Models.State { Id = location.MLocation.State.Id, Code = location.MLocation.State.Code, Name = location.MLocation.State.Name },
                                            Country = new Models.Country { Id = location.MLocation.Country.Id, Code = location.MLocation.Country.Code, Name = location.MLocation.Country.Name },
                                            Continent = new Models.Continent { Id = location.MLocation.Continent.Id, Code = location.MLocation.Continent.Code, Name = location.MLocation.Continent.Name }
                                        }
                                    }).ToList();
        }


        public ActionResult GetAllLinkDefinitions(string FromLocationCode = "0", string ToLocationCode = "0")
        {
            //List<Link> LstLinks = new List<Link>();
            Link ObjLinkModel = null;
            // List<Coordinate> AllLstLinkCoordinate = new List<Coordinate>();
            if (FromLocationCode != "0" && ToLocationCode != "0")
            {
                if (FromLocationCode != ToLocationCode)
                {
                    try
                    {
                        //var data1 = eeSeaWS.GetAllLinkDefinitionsOfLinkedLocations(long.Parse(FromLocationCode), long.Parse(ToLocationCode));
                        List<LinkDefinition> LstLnkDef = eeSeaWS.GetAllLinkDefinitionsOfLinkedLocations(long.Parse(FromLocationCode), long.Parse(ToLocationCode)).ToList();
                        if (LstLnkDef != null)
                        {
                            GPSLib oGPSLib = new GPSLib();
                            ObjLinkModel = new Link();

                            ObjLinkModel.LocationA = ((List<Models.Location>)Session["AllLocations"]).Where(da => da.Id == long.Parse(FromLocationCode)).SingleOrDefault();
                            ObjLinkModel.LocationB = ((List<Models.Location>)Session["AllLocations"]).Where(da => da.Id == long.Parse(ToLocationCode)).SingleOrDefault();

                            ObjLinkModel.Definition = LstLnkDef;
                            ObjLinkModel.MapCoordinates = new Dictionary<long, List<Coordinate>>();
                            ObjLinkModel.RandomColor = new Dictionary<long, System.Drawing.KnownColor>();
                            System.Random randonGen = new System.Random();
                            //string[] colorNames = Enum.GetNames(typeof(KnownColor));

eeSea/Views/Locations/GetLocationsResuls.cshtml
@model IEnumerable<eeSea.Models.Location>
@{
    Layout = null;
}
<link href="@Url.Content("~/Content/ui.jqgrid.css")" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="@Url.Content("~/Scripts/grid.locale-en.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.jqGrid.min.js")"></script>
<script type="text/javascript">



    var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-33927253-1']);

    _gaq.push(['_setDomainName', 'eesea.com']);

    _gaq.push(['_trackPageview']);



    (function () {

        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();

 

</script>
@if (Model != null)
{ 
    <table class="List" align="left" id="ListItems">
        <thead>
            <tr>
                <th  scope="col" width="10%">
                    Id
                </th>
                <th  scope="col"  width="25%">
                    Location Code
                </th>
                <th  scope="col"  width="25%">
                    Location Name
                </th>
                <th  scope="col"  width="20%">
                    Location Latitude
                </th>
                <th  scope="col"  width="20%">
                    Location Longitude
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr id="@item.Id">
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Latitude)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Longitude)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div id="pager" class="scroll" style="text-align: center;">
    </div> 
}
<script type="text/javascript">
    //<![CDATA[

    $(function () {

        myGrid2 = $("#ListItems");
        tableToGrid(myGrid2, {
            rowNum:10, 
            rowList:[10,20,30], 
            pager: '#pager', 
            sortname: 'id', 
            viewrecords: false, 
            sortorder: "desc", 
            caption:"Locations Search Results:",
            autowidth: true,
            forceFit: true,
           /*
           forceFit: true,
           viewrecords: true,
           hidegrid: true,
           gridview: true,
           autowidth: true,
           */
            height: 450,
            colNames: ['Id', 'Location Code', 'Location Name', 'Location Latitude', 'Location Longitude'],
                    colModel: [
                        { name: 'Id', index: 'Id', width: 30, hidden: true },
                        { name: 'Location_Code', index: 'Location_Code', width: 120 },
                        { name: 'Location_Name', index: 'Location_Name', width: 120 },
                        { name: 'Location_Latitude', index: 'Location_Latitude', width: 120 },
                        { name: 'Location_Longitude', index: 'Location_Longitude', width: 120 } 
                    ],
            onSelectRow: function(rowid) {

                var id = $(this).getCell(rowid,0);
                //alert("-" + id + "-");
                $("#data-grid").html("")
                .load("@Url.Content("~/Locations/LocationInfos/")" + $.trim(id));
                
            }
        });

        //autowidth: true,
        //width: '100%'
    });
</script>

eeSea/Views/Locations/Index.cshtml
@model eeSea.Models.Region
@{
    
    
    var @modelLocation = new eeSea.Models.Location();
    IEnumerable<eeSea.Models.Location> @modelLocations;
    
}
<script type="text/javascript">



    var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-33927253-1']);

    _gaq.push(['_setDomainName', 'eesea.com']);

    _gaq.push(['_trackPageview']);



    (function () {

        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();



</script>
<script src="@Url.Content("~/Content/js/fcts.js")" type="text/javascript"></script>
<style>
    input.ui-autocomplete-input {
        width: 200px;
    }
</style>
<table width="100%" border="0" id="tblContent">
    <tr>
        
        <td id="tdCont" height="500px" valign="top" align="center">
            <div id="loading" style="display: none;" class="innerDiv">
                <span style="color: #EE7409; font-size: 13px;">Please wait while loading data ...</span><br />
                <img style="align: center;" src="../Content/Images/ajax-loader.gif" alt="Loading, please wait" />
            </div>
            <div id="data-grid" style="overflow: auto;">
                @Html.Partial("GetLocationsResuls", (IEnumerable<eeSea.Models.Location>)ViewBag.Locations)
            </div>
          @*  <div id="data-grid1" style="overflow: auto; float: left">
                 @Html.Partial("GetAllLinkDefinitions", (eeSea.Models.Link)ViewBag.AllLocationLinks, new ViewDataDictionary(this.ViewData));
            </div>*@
        </td>
        <td valign="top" id="toggle">
            <div id='sideToggleShow'>
            </div>
            <div id='sideToggleHide' style="display: none">
            </div>
        </td>
        <td id='side' class='sideList' valign="top">
            @using (Ajax.BeginForm("GetLocationsResuls", "Locations", new AjaxOptions { UpdateTargetId = "data-grid", LoadingElementDuration = 1000, LoadingElementId = "loading", HttpMethod = "GET" }))
            {
                <table border="0" height="150px">
                    <tr align="left">
                        <td height="25px" colspan="2">Find a Location
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">Region:
                        </td>
                        <td>@Html.DropDownList("RegionId", new SelectList(ViewBag.Regions, "ID", "Name"), "-- Select Region --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">Location:
                        </td>
                        <td>@Html.DropDownList("LocationCode", Enumerable.Empty<SelectListItem>(), "-- Select Location --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px"></td>
                        <td>
                           
                            <input value="Go" type="submit" class="btnSearch" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                </table>
            }
            @*@using (Ajax.BeginForm("GetAllLinkDefinitions", "Locations", new AjaxOptions { UpdateTargetId = "data-grid1", LoadingElementDuration = 1000, LoadingElementId = "loading", HttpMethod = "GET" }))
            {
                <table border="0" height="225px">
                    <tr align="left">
                        <td height="25px" colspan="2">Find a Link
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">From:
                        </td>
                        <td>@Html.DropDownList("FromLocationCode", new SelectList((IEnumerable<eeSea.Models.Location>)Session["AllLocations"], "ID", "City.Name"), "-- Select Location --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">To:
                        </td>
                        <td>@Html.DropDownList("ToLocationCode", new SelectList((IEnumerable<eeSea.Models.Location>)Session["AllLocations"], "ID", "City.Name"), "-- Select Location --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px"></td>
                        <td>
                            <input value="Go" type="submit" class="btnSearch" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                </table>
            }*@
            <table height="50px" width="100%" border="0">
                <tr>
                    <td colspan="2" height="25px" width="100%">
                        <table width="">
                            <tr>
                                <td width="90%">
                                    <input id="SearchBox" type="text" style="width: 185px" value="Search..." />
                                </td>
                                <td align="left">
                                    <input value="Go" type="submit" class="btnSearch2" />
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>



</table>

<script type="text/javascript">
    $(document).ready(function () {
        //autocomplete text search
        $("#SearchBox").autocomplete({
            source: '@Url.Action("GetRegionsLocationsByName", "Locations")',
            select: function (event, ui) {
                $("#data-grid").html("")
                    .load(encodeURI("@Url.Content("~/Locations/GetLocationsResulsByTerm/?term=")" + ui.item.label));

            }
        });

        $("#SearchBox").focus(function (event, ui) {
            $(this).val('');
        });

        $("#SearchBox").keypress(function (event, ui) {
            //alert(event.keyCode);
            if (event.keyCode == '13') {
            }
        });

        $(".btnSearch2").click(function () {
            $("#data-grid").html("")
                .load(encodeURI("@Url.Content("~/Locations/GetLocationsResulsByTerm/?term=")" + $("#SearchBox").val()));


        });
        toggleSideBar();
    });




    $('#RegionId').change(function () {
        var selectedRegionID = $(this).val();
        //$('#PersonInformation_NationalityId').val(selectedCountryId);
        $.getJSON('@Url.Content("~/Locations/GetLocationByRegionId")', { regionID: selectedRegionID }, function (locations) {
            var locationSelect = $('#LocationCode');
            locationSelect.empty();
            locationSelect.append(
                        $('<option/>')
                            .attr('value', '0')
                            .text("-- Select Location --")
                    );
            $.each(locations, function (index, location) {
                locationSelect.append(
                        $('<option/>')
                            .attr('value', location.Code)
                            .text(location.Name)
                    );
            });
        });
    });

</script>

eeSea/Views/Locations/LocationInfos.cshtml
@model eeSea.Models.Location
@{
    Layout = null;    
}
 
<br />
<script type="text/javascript">



    var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-33927253-1']);

    _gaq.push(['_setDomainName', 'eesea.com']);

    _gaq.push(['_trackPageview']);



    (function () {

        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();

 

</script>
<table width="100%" height="500px" border="0" align="left" class=" ui-widget ui-widget-content ui-corner-all">
    <tr   align="left">
        <td colspan="5" height="35px" >
            <h3 class="ui-dialog-titlebar ui-widget-header ui-corner-all ui-helper-clearfix">
                @Html.DisplayFor(model => model.Name)</h3>
        </td>
    </tr>
    <tr   align="left">
        <td width="20%" height="35px">
            <b>Location Name</b>
        </td>
        <td width="20%" >@Html.DisplayFor(model => model.Name)
        </td>
         
        <td  width="20%" >
            <b>Country Name</b>
        </td>
        <td >
            @Html.DisplayFor(model => model.City.Country.Name)
        </td>
    </tr>
    <tr   align="left">
        <td  height="35px">
            <b>Location type</b>
        </td>
        <td>
            Port
        </td>
         
        <td>
            <b>Region name</b>
        </td>
        <td>
            @Html.DisplayFor(model => model.Region.Name)
        </td>
    </tr>
    <tr   align="left">
        <td height="35px">
            <b>UN code</b>
        </td>
        <td>@Html.DisplayFor(model => model.Code)
        </td>
       
        <td>
            <b>Continent name</b>
        </td>
        <td>
           @Html.DisplayFor(model => model.City.Continent.Name)
        </td>
    </tr>
    <tr   align="left">
        <td height="35px">
            <b>Latitude</b>
        </td>
        <td>@Html.DisplayFor(model => model.Latitude)
        </td>
         
        <td>
            <b>State</b>
        </td>
        <td>
            @Html.DisplayFor(model => model.City.State.Name)
        </td>
    </tr>
    <tr   align="left">
        <td height="35px">
            <b>Longitude</b>
        </td>
        <td>
            @Html.DisplayFor(model => model.Longitude)
        </td>
        <td>
             <b>City</b>
        </td>
      
        <td>
            @Html.DisplayFor(model => model.City.Name)
        </td>
    </tr>
    <tr   align="left">
        <td valign="top" colspan="2">
            <b>Description</b><br />
            @Html.DisplayFor(model => model.Name) was founded in lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
            lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
            lorem ipsum lorem ipsum lorem ipsum lorem ipsum Today Hong Kong is amongst the largest
            lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
            lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum
            lorem ipsum
        </td>
        <td colspan="2" align="right"  >
            @{

                if (@Request.Url.Host != "localhost")
                {
                <div id="map_canvas" style="width: 300px; height: 300px"></div> 
                
                <script type="text/javascript">
    function initialize() {
    
         var myLatlng = new google.maps.LatLng(@Model.Latitude, @Model.Longitude);
  var mapOptions = {
    zoom: 5,
    center: myLatlng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  }
  var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);

  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title:"@Model.Name"
  });
        
    }
    $(function () {
        initialize();
    });      
                </script> 
    
                }
            }
        </td>
    </tr>
</table>
<br />

eeSea/Views/Locations/Lookup.cshtml
 
 <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.layout-latest.js")" type="text/javascript"></script>
 
<script type="text/javascript">
    $(document).ready(function () {
        $('body').layout({ applyDemoStyles: true });
    });
</script>
 
<div class="ui-layout-center">Center
	<p><a href="http://layout.jquery-dev.net/demos.html">Go to the Demos page</a></p>
	<p>* Pane-resizing is disabled because ui.draggable.js is not linked</p>
	<p>* Pane-animation is disabled because ui.effects.js is not linked</p>
</div>
<div class="ui-layout-north">North</div>
<div class="ui-layout-south">South</div>
<div class="ui-layout-east">East</div>
<div class="ui-layout-west">West</div>
 