eeSea/Controllers/DistanceAndLinksController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Collections;
using eeSea.Models;
using eeSea.com.eesea.ws;
using System;
using System.Drawing;


namespace eeSea.Controllers
{
    public class DistanceAndLinksController : Controller
    {
        //
        // GET: /DistanceAndLinks/

        Transportal eeSeaWS = new Transportal();
        public ActionResult Index()
        {
            List<eeSea.Models.Location> locations = null;
            ViewBag.Locations = locations;

            List<eeSea.Models.Location> Alllocations = GetAllLocations();
            ViewBag.AllLocations = Alllocations;
            Session["AllLocations"] = Alllocations;
            return View();
        }
   
        public List<Models.Location> GetAllLocations()
        {
            return eeSeaWS.GetAllLocations().Select(location => new Models.Location
            {
                Id = location.Id,
                Code = location.Code,
                Name = location.Name,
                Latitude = location.Latitude,
                Longitude = location.Longitude,
                Region = new eeSea.Models.Region { Id = location.Region.Id, Name = location.Region.Name },
                City = new eeSea.Models.City
                {
                    Id = location.MLocation.Id,
                    Code = location.MLocation.Code,
                    Name = location.MLocation.Name,
                    State = new Models.State { Id = location.MLocation.State.Id, Code = location.MLocation.State.Code, Name = location.MLocation.State.Name },
                    Country = new Models.Country { Id = location.MLocation.Country.Id, Code = location.MLocation.Country.Code, Name = location.MLocation.Country.Name },
                    Continent = new Models.Continent { Id = location.MLocation.Continent.Id, Code = location.MLocation.Continent.Code, Name = location.MLocation.Continent.Name }
                }
            }).ToList();
        }

        public ActionResult GetAllLinkDefinitions(string FromLocationCode = "0", string ToLocationCode = "0")
        {
            //List<Link> LstLinks = new List<Link>();
            Link ObjLinkModel = null;
            // List<Coordinate> AllLstLinkCoordinate = new List<Coordinate>();
            if (FromLocationCode != "0" && ToLocationCode != "0")
            {
                if (FromLocationCode != ToLocationCode)
                {
                    try
                    {
                        //var data1 = eeSeaWS.GetAllLinkDefinitionsOfLinkedLocations(long.Parse(FromLocationCode), long.Parse(ToLocationCode));
                        List<LinkDefinition> LstLnkDef = eeSeaWS.GetAllLinkDefinitionsOfLinkedLocations(long.Parse(FromLocationCode), long.Parse(ToLocationCode)).ToList();
                        if (LstLnkDef != null)
                        {
                            GPSLib oGPSLib = new GPSLib();
                            ObjLinkModel = new Link();

                            ObjLinkModel.LocationA = ((List<Models.Location>)Session["AllLocations"]).Where(da => da.Id == long.Parse(FromLocationCode)).SingleOrDefault();
                            ObjLinkModel.LocationB = ((List<Models.Location>)Session["AllLocations"]).Where(da => da.Id == long.Parse(ToLocationCode)).SingleOrDefault();

                            ObjLinkModel.Definition = LstLnkDef;
                            ObjLinkModel.MapCoordinates = new Dictionary<long, List<Coordinate>>();
                            ObjLinkModel.RandomColor = new Dictionary<long, System.Drawing.KnownColor>();
                            System.Random randonGen = new System.Random();
                            //string[] colorNames = Enum.GetNames(typeof(KnownColor));
                            string[] colorNames = new string[13];

                            colorNames[0] = Enum.GetName(typeof(KnownColor), KnownColor.DarkBlue);
                            colorNames[1] = Enum.GetName(typeof(KnownColor), KnownColor.Red);
                            colorNames[2] = Enum.GetName(typeof(KnownColor), KnownColor.Green);
                            colorNames[3] = Enum.GetName(typeof(KnownColor), KnownColor.Yellow);
                            colorNames[4] = Enum.GetName(typeof(KnownColor), KnownColor.Black);
                            colorNames[5] = Enum.GetName(typeof(KnownColor), KnownColor.Brown);
                            colorNames[6] = Enum.GetName(typeof(KnownColor), KnownColor.DeepPink);
                            colorNames[7] = Enum.GetName(typeof(KnownColor), KnownColor.Purple);
                            colorNames[8] = Enum.GetName(typeof(KnownColor), KnownColor.Orange);
                            colorNames[9] = Enum.GetName(typeof(KnownColor), KnownColor.Silver);
                            colorNames[10] = Enum.GetName(typeof(KnownColor), KnownColor.Wheat);
                            colorNames[11] = Enum.GetName(typeof(KnownColor), KnownColor.DarkMagenta);
                            colorNames[12] = Enum.GetName(typeof(KnownColor), KnownColor.Gold);

                            List<KnownColor> lstcheckcolors = new List<KnownColor>();
                            foreach (LinkDefinition item in LstLnkDef)
                            {
                                var data = eeSeaWS.GetCoordinatesOfLinkDefinition(item.Id);
                                if (data != null)
                                {
                                    if (data.Count() > 0)
                                    {
                                        List<Coordinate> LstLinkCoordinate = data.ToList();
                                        ObjLinkModel.MapCoordinates.Add(item.Id, LstLinkCoordinate);
                                        KnownColor knownColor = (KnownColor)Enum.Parse(typeof(KnownColor), colorNames[randonGen.Next(1, 12)]);
                                        while (lstcheckcolors.Count != 12 && lstcheckcolors.Contains(knownColor))
                                        {
                                            knownColor = (KnownColor)Enum.Parse(typeof(KnownColor), colorNames[randonGen.Next(1, 12)]);
                                        }
                                        lstcheckcolors.Add(knownColor);
                                        ObjLinkModel.RandomColor.Add(item.Id, knownColor);


                                    }
                                }
                            }

                            ObjLinkModel.GMapJs = GPSLib.PlotGPSPtLocations(ObjLinkModel.MapCoordinates, ObjLinkModel.RandomColor);
                            //ObjLinkModel.GMapJs = GPSLib.PlotMainMap(ObjLinkModel.GMapJs);


                        }

                    }
                    catch { }
                }
            }
            Session["LinkModel"] = ObjLinkModel;

            return PartialView(ObjLinkModel);
        }

    }
}

eeSea/Views/DistanceAndLinks/DisplayGMap.cshtml
spl@model eeSea.Models.Link
@{
    Layout = null;
    
}

<!--Google API Javascript Reference-->
<link
    href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css"
    rel="stylesheet" type="text/css" />
<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=false"></script>

@if (Model != null)
{
   
    <div id="map_canvas" style="clear: both; width: 700px; height: 600px;"></div>

           
    
    if (Model != null)
    {
        if (Model.Definition != null)
        {
            if (Model.GMapJs != "")
            {
   

    <script type='text/javascript'>

        var poly;
        var map;

        function initialize1() {

            var cmloc = new google.maps.LatLng(24.5271348225978, -78.75);
            var myOptions = {
                zoom: 2,
                center: cmloc,
                mapTypeId: google.maps.MapTypeId.TERRAIN
            };
          
            map = new google.maps.Map(document.getElementById('map_canvas'), myOptions);
            @MvcHtmlString.Create(Model.GMapJs);
            

        }
        initialize1();
    </script>
              
            }
        }
    }

}

eeSea/Views/DistanceAndLinks/GetAllLinkDefinitions.cshtml
@model eeSea.Models.Link
@{
    Layout = null;
}
<link href="@Url.Content("~/Content/ui.jqgrid.css")" rel="stylesheet" type="text/css" />



<script type="text/javascript" src="@Url.Content("~/Scripts/grid.locale-en.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.jqGrid.min.js")"></script>


<!--Google API Javascript Reference-->
<link
    href="http://code.google.com/apis/maps/documentation/javascript/examples/default.css"
    rel="stylesheet" type="text/css" />
<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=false"></script>




@if (Model != null)
{
   
    <style>
        td, h2, tr, h4 {
            margin: 0px;
            padding: 0px;
        }
    </style>
    <h1 style="margin-left: 20px; text-decoration: underline; padding: 0px; margin-bottom: 20px;">@Html.DisplayFor(d => d.LocationA.City.Name) , @Html.DisplayFor(d => d.LocationA.City.Country.Name) <-> 
    @Html.DisplayFor(d => d.LocationB.City.Name) , @Html.DisplayFor(d => d.LocationB.City.Country.Name)  </h1>
    
    <table>

        <tr>
            <td style="width: 30%; vertical-align: top;text-align:left;margin:0px;padding:0px;">
                @if (Model.Definition != null)
                {
                    <table style="float: left; margin-left: 20px;margin-bottom: 20px;">
                        <tr>
                            <td style="width: 100px">
                                <h2>From</h2>
                            </td>
                            <td style="width: 100px">@Html.DisplayFor(d => d.LocationA.City.Name)</td>
                            <td></td>
                        </tr>
                        <tr>
                            <td style="width: 100px">
                                <h2>To</h2>
                            </td>
                            <td style="width: 100px">@Html.DisplayFor(d => d.LocationB.City.Name)</td>
                            <td style="width: 100px"></td>
                        </tr>

                    </table>

                    <table style="float: left; margin-left: 20px;">
                        <tr style="float: left;">
                            <td>
                                <h2>"Counts of links " </h2>
                            </td>
                        </tr>
                        <tr style="float: right; ">

                            <td>
                                <h2>@Html.Label(Model.Definition.Count.ToString())</h2>
                            </td>

                        </tr>
                    </table>
                
                    <table style="float: left; margin-left: 20px;">
                        @for (int i = 0; i < Model.Definition.Count; i++)
                        {
                            <tr>
                                <td colspan="2" style="font-weight: bold;">
                                    <h2>@Html.Label("Link  :  " + (i + 1).ToString())</h2>
                                </td>
                                <td></td>
                            </tr>
            
                            <tr>
                                <td>
                                    <h3 style="margin:0px">Name : </h3>
                                </td>
                                <td style="margin-left: 20px">@Html.DisplayFor(modelItem => Model.Definition[i].Name)
                                </td>
                                @*  <td>Image
                </td>*@
                            </tr>
            
                            <tr>
                                <td>
                                    <h3 style="margin:0px">Distance : </h3>
                                </td>
                                <td style="margin-left: 20px">@Html.DisplayFor(modelItem => Model.Definition[i].Distance) @Html.Label(" km")
                                </td>
                                @*<td>Image
                </td>*@
                            </tr>
                            <tr>
                                <td>
                                    <h3 style="margin:0px">Color : </h3>
                                </td>
                                <td style="margin-left: 20px">@Html.Label(Enum.GetName(typeof(System.Drawing.KnownColor), Model.RandomColor[Model.Definition[i].Id]))
                                </td>
                                @*<td>Image
                </td>*@
                            </tr>
            
                            <tr>
                                <td style="margin-bottom: 20px;" colspan="4">
                                    <br />
                                    <br />
                                    <br />
                                </td>
                            </tr>
                        }

                    </table>
                }
            </td>

            <td style="width: 65%; vertical-align: top;">
                <div>
                @Html.Partial("DisplayGMap")
                    </div>
            </td>
        </tr>
    </table>
    
 
    <div id="pager" class="scroll" style="text-align: center;">
    </div> 
}

eeSea/Views/DistanceAndLinks/Index.cshtml
@model eeSea.Models.Link 
@{
    
    
    //var @modelLocation = new eeSea.Models.Location();
    //IEnumerable<eeSea.Models.Location> @modelLocations;
    
    
}
<script type="text/javascript">



    var _gaq = _gaq || [];

    _gaq.push(['_setAccount', 'UA-33927253-1']);

    _gaq.push(['_setDomainName', 'eesea.com']);

    _gaq.push(['_trackPageview']);



    (function () {

        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;

        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';

        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);

    })();



</script>
<script src="@Url.Content("~/Content/js/fcts.js")" type="text/javascript"></script>
<style>
    input.ui-autocomplete-input {
        width: 200px;
    }
</style>
<table width="100%" border="0" id="tblContent">
    <tr>

        <td id="tdCont" height="500px" valign="top" align="center">
            <div id="loading" style="display: none;" class="innerDiv">
                <span style="color: #EE7409; font-size: 13px;">Please wait while loading data ...</span><br />
                <img style="align: center;" src="../Content/Images/ajax-loader.gif" alt="Loading, please wait" />
            </div>

            <div id="data-grid" style="overflow: auto; float: left">
                @Html.Partial("GetAllLinkDefinitions", (eeSea.Models.Link)ViewBag.AllLocationLinks, new ViewDataDictionary(this.ViewData))
            </div>
        </td>
        <td valign="top" id="toggle">
            <div id='sideToggleShow'>
            </div>
            <div id='sideToggleHide' style="display: none">
            </div>
        </td>
        <td id='side' class='sideList' valign="top">

            @using (Ajax.BeginForm("GetAllLinkDefinitions", "DistanceAndLinks", new AjaxOptions { UpdateTargetId = "data-grid", LoadingElementDuration = 1000, LoadingElementId = "loading", HttpMethod = "GET" }))
            {
                <table border="0" height="225px">
                    <tr align="left">
                        <td height="25px" colspan="2">Find a Link
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">From:
                        </td>
                        <td>@Html.DropDownList("FromLocationCode", new SelectList((IEnumerable<eeSea.Models.Location>)Session["AllLocations"], "ID", "City.Name"), "-- Select Location --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px">To:
                        </td>
                        <td>@Html.DropDownList("ToLocationCode", new SelectList((IEnumerable<eeSea.Models.Location>)Session["AllLocations"], "ID", "City.Name"), "-- Select Location --", new { @class = "ui-widget search-dropdown" })
                        </td>
                    </tr>
                    <tr align="left">
                        <td height="25px"></td>
                        <td>
                          
                            <input value="Go" onclick="toggleSideBar();" type="submit" class="btnSearch" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2"></td>
                    </tr>
                </table>
            }

        </td>
    </tr>



</table>
<script type="text/javascript">
    $(document).ready(function () {



        toggleSideBar();
    });






</script>